<a href="https://colab.research.google.com/github/hariThorve/tensorflow/blob/main/00_tensorflowFundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print(tf.__version__)

2.17.1


In [2]:
# create tensor with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# check number of dimensions of the tensor (ndim stands for numoy dimensions)

scalar.ndim

0

In [4]:
# create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# check dimensions of the vector

vector.ndim

1

In [6]:
# create a matrix

matrix = tf.constant([[10, 7], [1, 2]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 1,  2]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
# creating a tensor of datatype float

tensor = tf.constant([[[1., 2., 3.],
                       [4., 5., 6.]],
                      [[7., 8., 9.],
                       [10., 11., 12.]],
                      [[13., 14., 15.],
                       [16., 17., 18.]]], dtype=tf.float16)
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=float16, numpy=
array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 7.,  8.,  9.],
        [10., 11., 12.]],

       [[13., 14., 15.],
        [16., 17., 18.]]], dtype=float16)>

In [9]:
tensor.ndim

3

# What we created so far
* Scalar: a single number
* Vector: Number with direction
* Matrix: a 2 - dimensional array of numbers
* Tensor: an n-directional array of numbers (a 0-dimensional array is scalar and 1-dimensional array is a vector)



### Creating tensor with `tf.Variable`

In [10]:
# create a similar tensor using tf.variable

changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 10])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>)

In [11]:
# Lets try to change the value of "changeable_tensor"

# changeable_tensor[0] = 7
# above line gives following error

# TypeError                                 Traceback (most recent call last)
# <ipython-input-15-c12697976491> in <cell line: 3>()
#       1 # Lets try to change the value of "changeable_tensor"
#       2
# ----> 3 changeable_tensor[0] = 7

# TypeError: 'ResourceVariable' object does not support item assignment


In [12]:
#Lets try another method that is

changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [13]:
# Let's try similar with "unchangeable_tensor"

# unchangeable_tensor[0].assign(7)

#above line gives error

# AttributeError                            Traceback (most recent call last)
# <ipython-input-17-727e1931d5de> in <cell line: 3>()
#       1 # Let's try similar with "unchangeable_tensor"
#       2
# ----> 3 unchangeable_tensor[0].assign(7)

# /usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/tensor.py in __getattr__(self, name)
#     258         tf.experimental.numpy.experimental_enable_numpy_behavior()
#     259       """)
# --> 260     self.__getattribute__(name)
#     261
#     262   @property

# AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

* So tensors made using `tf.Variable` are changeable
* Whereas tensors made using `tf.constant` are constant and cannot be changed

## Creating an random tensor

In [14]:
random1 = tf.random.Generator.from_seed(42) #set seed for reproducibility
random1 = random1.normal(shape=(3, 2))
random2 = tf.random.Generator.from_seed(42)
random2 = random2.normal(shape = (3, 2))
random1, random2, random1 == random2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

## Shuffling of tensors

In [15]:
not_shuffled = tf.constant([[1, 2],
                            [3, 4],
                            [5, 6]])
tf.random.shuffle(not_shuffled) # shuffle value changes constantly and does not remain same

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [5, 6],
       [3, 4]], dtype=int32)>

In [16]:
# by assigning seed we would prvent the constant shuffling
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

## Other ways to create a tensor

## Converting numpy array into tensor

> Differnce between numpy and tensor is only that the tensor run faster on the GPU

In [17]:
## Converting numpy array into tensor

import numpy as np

numpy_A = np.arange(1, 25, dtype= np.int32)
numpy_A

numpy_tensor = tf.constant(numpy_A, shape =(2, 3, 4))
numpy_tensor

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [18]:
# Creting a tensor of all ones

onesTensor = tf.ones([3, 4]) ## by default values are assigned float
onesTensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [19]:
# Creating a tensor of all zeros

zeroTensor = tf.zeros(shape = (3, 4), dtype = tf.int32)
zeroTensor

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)>

## Get information from the tensor

### Following are the attributes of the tensor
 * Size
 * Shape
 * Axis of dimensions
 * Rank

In [20]:
# Create a tensor of rank 4 (that is tensor with 4 dimensions)

rank_4_tensor = tf.zeros([2, 3 , 4, 5], dtype = tf.int32)
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int32, numpy=
array([[[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]],


       [[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]]], dtype=int32)>

In [21]:
# Getting to know about various attributes of "rank_4_tensor"

print("Datatype of the tensor: ", rank_4_tensor.dtype)
print("Shape of the tensor: ", rank_4_tensor.shape)
print("Number of dimensions in the tensor: ", rank_4_tensor.ndim)
print("Number of elements along the 0 axis of tensor: ", rank_4_tensor.shape[0])
print("Number of elements along the last axis of the tensor: ", rank_4_tensor.shape[-1])
print("Number of elements in the tensor: ", tf.size(rank_4_tensor))
print("Number of elements in the tensor: ", tf.size(rank_4_tensor).numpy())

Datatype of the tensor:  <dtype: 'int32'>
Shape of the tensor:  (2, 3, 4, 5)
Number of dimensions in the tensor:  4
Number of elements along the 0 axis of tensor:  2
Number of elements along the last axis of the tensor:  5
Number of elements in the tensor:  tf.Tensor(120, shape=(), dtype=int32)
Number of elements in the tensor:  120


# Indexing of tensors


In [22]:
rank2Tensor = tf.constant([[1, 2],
                           [3, 4]])
rank2Tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [23]:
# Getting only 1st element from each array
rank2Tensor[:, :1]

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[1],
       [3]], dtype=int32)>

In [24]:
# Getting only last element from each array
rank2Tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [25]:
# adding a new dimension to the tensor
rank3Tensor = rank2Tensor[..., tf.newaxis]
# rank3Tensor = rank2Tensor[:, :, tf.newaxis] ... also represents :, meanswithout changing the previous axis
rank3Tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [26]:
#another way to add axis is
tf.expand_dims(rank2Tensor, axis = -1)  # "-1" means expand to the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

# manipulating Tensors with basic mathematical operations

In [27]:
newTensor = tf.constant([[1, 2],
                         [3, 4]])
newTensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [28]:
# Addition Operation

newTensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [29]:
# Multiplicaiton operation

newTensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [30]:
# Same for division and subtraction
# Another method to perform operation is

tensorAddition = tf.math.add(newTensor, 10) # for addition
tensorSubtraction = tf.math.subtract(newTensor, 10) # for subtracting
tensorMultiplication = tf.math.multiply(newTensor, 10) # for multiplication
tensorDivision = tf.math.divide(newTensor, 10) #for division

print(tensorAddition)
print(tensorSubtraction)
print(tensorMultiplication)
print(tensorDivision)

tf.Tensor(
[[11 12]
 [13 14]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[-9 -8]
 [-7 -6]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[10 20]
 [30 40]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[0.1 0.2]
 [0.3 0.4]], shape=(2, 2), dtype=float64)


# Note
* Using `tf.math.` is more efficient as it comes with abilities of tensorflow and can help performing operations more faster on the GPU as compared to `tensor + 10`

# Matrix Multiplication
* multiplying matrix/tensors with another matrix/tensor
* for this operation we use `tf.linalg.matmul` which stands for linear algebra and matrix multiplication


In [31]:
# lets create two tensor to demonstrate matrix multiplication
matTensor1 = tf.constant([[1, 2, 5],
                         [7, 2, 1],
                         [3, 3, 3]])
matTensor2 = tf.constant([[3, 5],
                          [6, 7],
                          [1, 8]])
matTensor1, matTensor2

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>)

In [32]:
tf.linalg.matmul(matTensor1, matTensor2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

# Remember when multiplying two tensors with each other

* The number of columns of the 1st matrix must equal the number of rows of the 2nd matrix.
* And the result will have the same number of rows as the 1st matrix, and the same number of columns as the 2nd matrix.

> * For example multiplying two matrcies with shape (2, 3) and (2, 3) that is the same shape will return the error.
* As the number of columns in first matrix/tensor that is 2 does not match the number of rows in second tensor that is 3.
* Hence to avoid this problem one of the two tensor need to change its shape this can be done using two methods
* `tf.reshape(tensor1 , shape=(3,2))` changing shape of first tensor.
* Or `tf.transpose(tensor1)`

### Difference between `tf.reshape` and `tf.transpose`
`tf.reshape`: changes the shape of the tensor randomly
`tf.transpose`: changes the axis of the tensor, means changing rows to columns and columns to rows.


In [33]:
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
# lets multiply x and y

#operation =  tf.matmul(X, y)

# error :
# ---------------------------------------------------------------------------
# InvalidArgumentError                      Traceback (most recent call last)
# <ipython-input-36-e74340f1c6c4> in <cell line: 9>()
#       7 # lets multiply x and y
#       8
# ----> 9 tf.matmul(X, y)

# 2 frames
# /usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/ops.py in raise_from_not_ok_status(e, name)
#    5981 def raise_from_not_ok_status(e, name) -> NoReturn:
#    5982   e.message += (" name: " + str(name if name is not None else ""))
# -> 5983   raise core._status_to_exception(e) from None  # pylint: disable=protected-access
#    5984
#    5985

# InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name:

In [34]:
# lets reshape either X or y
tf.reshape(X, shape = (2, 3))

# now multiply new X with y

tf.matmul(tf.reshape(X, shape = (2, 3)), y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [35]:
# now lets transpose any one of the tensors
tf.transpose(X)

# now multiply transposed x and y

tf.matmul(tf.transpose(X), y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [36]:
print("X : ", X)
print("\n Y: ", y)
print("\n reshaped X and y : ", tf.reshape(X, shape = (2, 3)),"\n", tf.reshape(y, shape = (2, 3)))
print("\n transposed X and y : ", tf.transpose(X),"\n", tf.transpose(y))

X :  tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)

 Y:  tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)

 reshaped X and y :  tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32) 
 tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)

 transposed X and y :  tf.Tensor(
[[1 3 5]
 [2 4 6]], shape=(2, 3), dtype=int32) 
 tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


# Finding Variance and Standard deviation of the tesnor




In [40]:
import random
E = tf.constant(np.random.randint(1, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 6, 69, 89, 40, 18, 37,  1, 84, 23, 64, 20, 74,  7, 59, 86, 49, 23,
       34, 24, 97, 60, 75, 42, 71, 13, 40, 16, 11, 18, 55,  8, 51, 98, 33,
       11, 88, 35, 50, 50, 57, 43, 71, 62, 48, 33, 88, 78, 88, 14, 41])>

In [45]:
# standard deviation
stdv = tf.math.reduce_std(tf.cast(E, dtype = tf.float32)) #typecasting int to float

# variance
variance = tf.math.reduce_variance(tf.cast(E, dtype = tf.float32))

stdv, variance

(<tf.Tensor: shape=(), dtype=float32, numpy=27.468498>,
 <tf.Tensor: shape=(), dtype=float32, numpy=754.51843>)

# Finding Positional maximum and minimum values of tensor



In [51]:
tf.random.set_seed(42)
F = tf.random.uniform(shape = [50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [54]:
# Finding positional maximum value

maxIndex = tf.argmax(F)
print("Index of maximum value: ", maxIndex)
print("Maximum value: ", F[maxIndex])

#Finding positional Minimum value

minIndex = tf.argmin(F)
print("Index of minimum value: ", minIndex)
print("Minimum value: ", F[minIndex])

Index of maximum value:  tf.Tensor(42, shape=(), dtype=int64)
Maximum value:  tf.Tensor(0.9671384, shape=(), dtype=float32)
Index of minimum value:  tf.Tensor(16, shape=(), dtype=int64)
Minimum value:  tf.Tensor(0.009463668, shape=(), dtype=float32)


# Squeezing a tensor

In [57]:
G = tf.constant(tf.random.uniform(shape = [50]), shape = [1, 1, 1, 50])
G, G.shape

(<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
 array([[[[0.7402308 , 0.33938193, 0.5692506 , 0.44811392, 0.29285502,
           0.4260056 , 0.62890387, 0.691061  , 0.30925727, 0.89236605,
           0.66396606, 0.30541587, 0.8724164 , 0.1025728 , 0.56819403,
           0.25427842, 0.7253866 , 0.4770788 , 0.46289814, 0.88944995,
           0.6792555 , 0.09752727, 0.01609659, 0.4876021 , 0.5832968 ,
           0.41212583, 0.731905  , 0.93418944, 0.5298122 , 0.9664817 ,
           0.88391197, 0.10578597, 0.44439578, 0.7851516 , 0.47332513,
           0.89893615, 0.04290593, 0.8717004 , 0.6068529 , 0.12963045,
           0.4527359 , 0.24573493, 0.34777248, 0.582147  , 0.82298195,
           0.82862926, 0.877372  , 0.5319803 , 0.03594303, 0.03986669]]]],
       dtype=float32)>,
 TensorShape([1, 1, 1, 50]))

In [58]:
G_squeezed = tf.squeeze(G)
G_squeezed.shape, G_squeezed

(TensorShape([50]),
 <tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.7402308 , 0.33938193, 0.5692506 , 0.44811392, 0.29285502,
        0.4260056 , 0.62890387, 0.691061  , 0.30925727, 0.89236605,
        0.66396606, 0.30541587, 0.8724164 , 0.1025728 , 0.56819403,
        0.25427842, 0.7253866 , 0.4770788 , 0.46289814, 0.88944995,
        0.6792555 , 0.09752727, 0.01609659, 0.4876021 , 0.5832968 ,
        0.41212583, 0.731905  , 0.93418944, 0.5298122 , 0.9664817 ,
        0.88391197, 0.10578597, 0.44439578, 0.7851516 , 0.47332513,
        0.89893615, 0.04290593, 0.8717004 , 0.6068529 , 0.12963045,
        0.4527359 , 0.24573493, 0.34777248, 0.582147  , 0.82298195,
        0.82862926, 0.877372  , 0.5319803 , 0.03594303, 0.03986669],
       dtype=float32)>)

# One hot encoding a tensor

In [59]:
H = tf.constant([1, 2, 3, 4])
H

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [62]:
#applying one hot encoding on the tensor

encodedH = tf.one_hot(H, depth = 4)
encodedH

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>