<a href="https://colab.research.google.com/github/hariThorve/tensorflow/blob/main/00_tensorflowFundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print(tf.__version__)

2.17.1


In [2]:
# create tensor with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# check number of dimensions of the tensor (ndim stands for numoy dimensions)

scalar.ndim

0

In [4]:
# create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# check dimensions of the vector

vector.ndim

1

In [6]:
# create a matrix

matrix = tf.constant([[10, 7], [1, 2]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 1,  2]], dtype=int32)>

In [7]:
matrix.ndim

2

In [9]:
# creating a tensor of datatype float

tensor = tf.constant([[[1., 2., 3.],
                       [4., 5., 6.]],
                      [[7., 8., 9.],
                       [10., 11., 12.]],
                      [[13., 14., 15.],
                       [16., 17., 18.]]], dtype=tf.float16)
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=float16, numpy=
array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 7.,  8.,  9.],
        [10., 11., 12.]],

       [[13., 14., 15.],
        [16., 17., 18.]]], dtype=float16)>

In [12]:
tensor.ndim

3

# What we created so far
* Scalar: a single number
* Vector: Number with direction
* Matrix: a 2 - dimensional array of numbers
* Tensor: an n-directional array of numbers (a 0-dimensional array is scalar and 1-dimensional array is a vector)



### Creating tensor with `tf.Variable`

In [14]:
# create a similar tensor using tf.variable

changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 10])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>)

In [19]:
# Lets try to change the value of "changeable_tensor"

# changeable_tensor[0] = 7
# above line gives following error

# TypeError                                 Traceback (most recent call last)
# <ipython-input-15-c12697976491> in <cell line: 3>()
#       1 # Lets try to change the value of "changeable_tensor"
#       2
# ----> 3 changeable_tensor[0] = 7

# TypeError: 'ResourceVariable' object does not support item assignment


In [16]:
#Lets try another method that is

changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [18]:
# Let's try similar with "unchangeable_tensor"

# unchangeable_tensor[0].assign(7)

#above line gives error

# AttributeError                            Traceback (most recent call last)
# <ipython-input-17-727e1931d5de> in <cell line: 3>()
#       1 # Let's try similar with "unchangeable_tensor"
#       2
# ----> 3 unchangeable_tensor[0].assign(7)

# /usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/tensor.py in __getattr__(self, name)
#     258         tf.experimental.numpy.experimental_enable_numpy_behavior()
#     259       """)
# --> 260     self.__getattribute__(name)
#     261
#     262   @property

# AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

* So tensors made using `tf.Variable` are changeable
* Whereas tensors made using `tf.constant` are constant and cannot be changed