<a href="https://colab.research.google.com/github/hariThorve/tensorflow/blob/main/00_tensorflowFundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print(tf.__version__)

2.17.1


In [2]:
# create tensor with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# check number of dimensions of the tensor (ndim stands for numoy dimensions)

scalar.ndim

0

In [4]:
# create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# check dimensions of the vector

vector.ndim

1

In [6]:
# create a matrix

matrix = tf.constant([[10, 7], [1, 2]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 1,  2]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
# creating a tensor of datatype float

tensor = tf.constant([[[1., 2., 3.],
                       [4., 5., 6.]],
                      [[7., 8., 9.],
                       [10., 11., 12.]],
                      [[13., 14., 15.],
                       [16., 17., 18.]]], dtype=tf.float16)
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=float16, numpy=
array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 7.,  8.,  9.],
        [10., 11., 12.]],

       [[13., 14., 15.],
        [16., 17., 18.]]], dtype=float16)>

In [9]:
tensor.ndim

3

# What we created so far
* Scalar: a single number
* Vector: Number with direction
* Matrix: a 2 - dimensional array of numbers
* Tensor: an n-directional array of numbers (a 0-dimensional array is scalar and 1-dimensional array is a vector)



### Creating tensor with `tf.Variable`

In [10]:
# create a similar tensor using tf.variable

changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 10])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>)

In [11]:
# Lets try to change the value of "changeable_tensor"

# changeable_tensor[0] = 7
# above line gives following error

# TypeError                                 Traceback (most recent call last)
# <ipython-input-15-c12697976491> in <cell line: 3>()
#       1 # Lets try to change the value of "changeable_tensor"
#       2
# ----> 3 changeable_tensor[0] = 7

# TypeError: 'ResourceVariable' object does not support item assignment


In [12]:
#Lets try another method that is

changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [13]:
# Let's try similar with "unchangeable_tensor"

# unchangeable_tensor[0].assign(7)

#above line gives error

# AttributeError                            Traceback (most recent call last)
# <ipython-input-17-727e1931d5de> in <cell line: 3>()
#       1 # Let's try similar with "unchangeable_tensor"
#       2
# ----> 3 unchangeable_tensor[0].assign(7)

# /usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/tensor.py in __getattr__(self, name)
#     258         tf.experimental.numpy.experimental_enable_numpy_behavior()
#     259       """)
# --> 260     self.__getattribute__(name)
#     261
#     262   @property

# AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

* So tensors made using `tf.Variable` are changeable
* Whereas tensors made using `tf.constant` are constant and cannot be changed

## Creating an random tensor

In [14]:
random1 = tf.random.Generator.from_seed(42) #set seed for reproducibility
random1 = random1.normal(shape=(3, 2))
random2 = tf.random.Generator.from_seed(42)
random2 = random2.normal(shape = (3, 2))
random1, random2, random1 == random2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

## Shuffling of tensors

In [15]:
not_shuffled = tf.constant([[1, 2],
                            [3, 4],
                            [5, 6]])
tf.random.shuffle(not_shuffled) # shuffle value changes constantly and does not remain same

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [16]:
# by assigning seed we would prvent the constant shuffling
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

## Other ways to create a tensor

## Converting numpy array into tensor

> Differnce between numpy and tensor is only that the tensor run faster on the GPU

In [17]:
## Converting numpy array into tensor

import numpy as np

numpy_A = np.arange(1, 25, dtype= np.int32)
numpy_A

numpy_tensor = tf.constant(numpy_A, shape =(2, 3, 4))
numpy_tensor

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [18]:
# Creting a tensor of all ones

onesTensor = tf.ones([3, 4]) ## by default values are assigned float
onesTensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [19]:
# Creating a tensor of all zeros

zeroTensor = tf.zeros(shape = (3, 4), dtype = tf.int32)
zeroTensor

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)>

## Get information from the tensor

### Following are the attributes of the tensor
 * Size
 * Shape
 * Axis of dimensions
 * Rank

In [20]:
# Create a tensor of rank 4 (that is tensor with 4 dimensions)

rank_4_tensor = tf.zeros([2, 3 , 4, 5], dtype = tf.int32)
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int32, numpy=
array([[[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]],


       [[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]]], dtype=int32)>

In [21]:
# Getting to know about various attributes of "rank_4_tensor"

print("Datatype of the tensor: ", rank_4_tensor.dtype)
print("Shape of the tensor: ", rank_4_tensor.shape)
print("Number of dimensions in the tensor: ", rank_4_tensor.ndim)
print("Number of elements along the 0 axis of tensor: ", rank_4_tensor.shape[0])
print("Number of elements along the last axis of the tensor: ", rank_4_tensor.shape[-1])
print("Number of elements in the tensor: ", tf.size(rank_4_tensor))
print("Number of elements in the tensor: ", tf.size(rank_4_tensor).numpy())

Datatype of the tensor:  <dtype: 'int32'>
Shape of the tensor:  (2, 3, 4, 5)
Number of dimensions in the tensor:  4
Number of elements along the 0 axis of tensor:  2
Number of elements along the last axis of the tensor:  5
Number of elements in the tensor:  tf.Tensor(120, shape=(), dtype=int32)
Number of elements in the tensor:  120


# Indexing of tensors


In [22]:
rank2Tensor = tf.constant([[1, 2],
                           [3, 4]])
rank2Tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [23]:
# Getting only 1st element from each array
rank2Tensor[:, :1]

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[1],
       [3]], dtype=int32)>

In [24]:
# Getting only last element from each array
rank2Tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [25]:
# adding a new dimension to the tensor
rank3Tensor = rank2Tensor[..., tf.newaxis]
# rank3Tensor = rank2Tensor[:, :, tf.newaxis] ... also represents :, meanswithout changing the previous axis
rank3Tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [26]:
#another way to add axis is
tf.expand_dims(rank2Tensor, axis = -1)  # "-1" means expand to the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

# manipulating Tensors with basic mathematical operations

In [27]:
newTensor = tf.constant([[1, 2],
                         [3, 4]])
newTensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [28]:
# Addition Operation

newTensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [29]:
# Multiplicaiton operation

newTensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [32]:
# Same for division and subtraction
# Another method to perform operation is

tensorAddition = tf.math.add(newTensor, 10) # for addition
tensorSubtraction = tf.math.subtract(newTensor, 10) # for subtracting
tensorMultiplication = tf.math.multiply(newTensor, 10) # for multiplication
tensorDivision = tf.math.divide(newTensor, 10) #for division

print(tensorAddition)
print(tensorSubtraction)
print(tensorMultiplication)
print(tensorDivision)

tf.Tensor(
[[11 12]
 [13 14]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[-9 -8]
 [-7 -6]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[10 20]
 [30 40]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[0.1 0.2]
 [0.3 0.4]], shape=(2, 2), dtype=float64)


# Note
* Using `tf.math.` is more efficient as it comes with abilities of tensorflow and can help performing operations more faster on the GPU as compared to `tensor + 10`